#!/bin/bash
#lweb = linux web
tun0=$(/sbin/ifconfig tun0 | grep 'inet' | head -1 | awk '{print $2}')
port=9000
for f in *; do
        echo "wget http://$tun0:$port/$f"
done

python -m SimpleHTTPServer $port
